policies: create sets with auto-merge by default
This will avoid the error:

Error: conflicting intervals specified

when creating a set with overlapped elements.

It is missing to fix the asymmetry of elements in nftlb side.

Signed-off-by: nevola <laura.garcia@zevenet.com>